### ISSUE TITLE
关于2d网络的训练

### ISSUE THREAD

**Issue by brueyq** [dcy0577/Enhancing-3D-Point-Cloud-Segmentation-Using-Multi-Modal-Fusion-with-2D-Images#6]
您好，抱歉打扰您，请问您在训练2d图像的时候有遇到seg_iou为nan的情况吗。在迭代2000的时候出现，在40000的时候验证seg_iou很低只有0.079，有的迭代还是nan。不管怎么样精度都提升不上去。希望能得到您的回复，万分感谢
![image](https://user-images.githubusercontent.com/46115914/194028547-50a4a460-9b19-4766-84bc-06d62664cf13.png)
![image](https://user-images.githubusercontent.com/46115914/194028935-1df1968e-c9ca-4ff0-ab04-1f55b5cc218d.png)

**Comment by dcy0577** [comment]
您好，如果您是使用scannet的话请检查一下数据预处理是否都做对了。如果是自定义的数据集，您可以查看您的yaml配置文件是否正确，例如num_classes, 也可以尝试调整学习率。
